package br.com.jorgereidinaldo.juno.classes;
// Generated 13/05/2020 16:53:37 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * RetornoPagamentoJuno generated by hbm2java
 */
public class RetornoPagamentoJuno implements java.io.Serializable {

	private int idRetornoPagamentoJuno;
	private Date dueDate;
	private String code;
	private String payNumber;
	private Date date;
	private String link;
	private BigDecimal amount;
	private BigDecimal fee;
	private String type;
	private String status;
	private String bankAccount;
	private String ourNumber;

	public RetornoPagamentoJuno() {
	}

	public RetornoPagamentoJuno(int idRetornoPagamentoJuno) {
		this.idRetornoPagamentoJuno = idRetornoPagamentoJuno;
	}

	public RetornoPagamentoJuno(int idRetornoPagamentoJuno, Date dueDate, String code, String payNumber, Date date,
			String link, BigDecimal amount, BigDecimal fee, String type, String status, String bankAccount,
			String ourNumber) {
		this.idRetornoPagamentoJuno = idRetornoPagamentoJuno;
		this.dueDate = dueDate;
		this.code = code;
		this.payNumber = payNumber;
		this.date = date;
		this.link = link;
		this.amount = amount;
		this.fee = fee;
		this.type = type;
		this.status = status;
		this.bankAccount = bankAccount;
		this.ourNumber = ourNumber;
	}

	public int getIdRetornoPagamentoJuno() {
		return this.idRetornoPagamentoJuno;
	}

	public void setIdRetornoPagamentoJuno(int idRetornoPagamentoJuno) {
		this.idRetornoPagamentoJuno = idRetornoPagamentoJuno;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPayNumber() {
		return this.payNumber;
	}

	public void setPayNumber(String payNumber) {
		this.payNumber = payNumber;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getOurNumber() {
		return this.ourNumber;
	}

	public void setOurNumber(String ourNumber) {
		this.ourNumber = ourNumber;
	}

}
